### ISSUE TITLE
refuel a VIP rank jetpack

### ISSUE THREAD

**Issue by Pelmen4ick** [adi-itgg/FJetpackReloaded#3]
hello, I have a problem with the fjetpackreloaded plugin, namely with a permission to refuel a VIP rank jetpack, it does not want to work

**Comment by adi-itgg** [comment]
> hello, I have a problem with the fjetpackreloaded plugin, namely with a permission to refuel a VIP rank jetpack, it does not want to work

can you show the config jetpacks here?

**Comment by adi-itgg** [comment]
fix not work for op/admin perms in commit [363a0da](https://github.com/adi-itgg/FJetpackReloaded/commit/363a0dace11d7a3fea789cad0bad8d1c305fa55d)

**Comment by Pelmen4ick** [comment]
Hello, it's me again with the same problem. You probably misunderstood me, when I try to give rights to ordinary players to refuel a jet pack, it doesn't work and writes to them that they don't have enough rights for this

**Comment by Pelmen4ick** [comment]
Thank you very much
