### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by leomanjos** [adi-itgg/FJetpackReloaded#6]
Hello, I've I issue that I found on language.

This translation is nowhere to be found:

![image](https://user-images.githubusercontent.com/58405267/214439268-5ddf2fa6-d88f-4fe1-9182-d24dce4bd1ac.png)

Or maybe I'm wrong?

Thanks for your help :)

**Comment by adi-itgg** [comment]
i see, no you're right. i will fix it later

Thanks for reporting this issue

**Comment by adi-itgg** [comment]
@leomanjos try my new plugin here [Spigot](https://www.spigotmc.org/resources/fjetpack2reloaded.107883/) a lot improvement and bugs fix, if you find some bugs you can open issue right [here](https://github.com/adi-itgg/FJetpack2Reloaded/issues)

**Comment by leomanjos** [comment]
Thanks alot @adi-itgg :)

**Comment by adi-itgg** [comment]
> Thanks alot @adi-itgg :)

You're welcome :)
